/** Accept only the loopback address and path generated by the CLI. */
export function parseCliCallback(params: URLSearchParams): { url: string; state: string } | null {
  const value = params.get("callback");
  const state = params.get("state");
  if (!value || !state || !/^[A-Za-z0-9_-]{43}$/.test(state)) return null;
  try {
    const url = new URL(value);
    if (
      url.protocol !== "http:" ||
      url.hostname !== "127.0.0.1" ||
      Number(url.port) < 1024 ||
      url.pathname !== "/callback" ||
      url.username ||
      url.password ||
      url.search ||
      url.hash
    )
      return null;
    return { url: url.href, state };
  } catch {
    return null;
  }
}

export async function sendCliCallback(callback: { url: string; state: string }, token: string) {
  const response = await fetch(callback.url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ token, state: callback.state }),
    credentials: "omit",
    redirect: "error",
    signal: AbortSignal.timeout(15_000),
  });
  if (!response.ok || (await response.json()).ok !== true) throw new Error("Callback failed");
}
