import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  layout("routes/app-frame.tsx", [
    index("routes/workspace.tsx"),
    route("library", "routes/workspace-library.tsx"),
    route("standard-ebooks", "routes/workspace-standard-ebooks.tsx"),
  ]),
  layout("routes/library.tsx", [route("books/:id/details", "routes/book-details.tsx")]),
  route("login", "routes/login.tsx"),
  route("settings", "routes/settings.tsx"),
  route("about", "routes/about.tsx"),
  route("share/:id", "routes/share.$id.tsx"),
  route("api/standard-ebooks/search", "routes/api.standard-ebooks.search.ts"),
  route("api/standard-ebooks/new-releases", "routes/api.standard-ebooks.new-releases.ts"),
  route("api/standard-ebooks/download", "routes/api.standard-ebooks.download.ts"),
  route("api/chat", "routes/api.chat.ts"),
  route("api/chat/resume/:sessionId", "routes/api.chat.resume.$sessionId.ts"),
  route("api/chat/messages/:sessionId", "routes/api.chat.messages.$sessionId.ts"),
  route("api/chat-title", "routes/api.chat-title.ts"),
  route("api/bug-report", "routes/api.bug-report.ts"),
  route("api/bug-reports", "routes/api.bug-reports.ts"),
  route("api/admin/llms.txt", "routes/api.admin.llms.txt.ts"),
  route("api/admin/bug-reports", "routes/api.admin.bug-reports.ts"),
  route("api/books/:bookId/chapters", "routes/api.books.$bookId.chapters.ts"),
  route("api/books/:bookId/artifacts", "routes/api.books.$bookId.artifacts.ts"),
  route("api/books/:bookId/artifacts/ingest", "routes/api.books.$bookId.artifacts.ingest.ts"),
  route("api/books/:bookId/artifacts/revisions", "routes/api.books.$bookId.artifacts.revisions.ts"),
  route("api/share", "routes/api.share.ts"),
  route("api/share/:id", "routes/api.share.$id.ts"),
  route("api/share/:id/chats", "routes/api.share.$id.chats.ts"),
  route("api/share/:id/cover", "routes/api.share.$id.cover.ts"),
  route("api/share/:id/notebook", "routes/api.share.$id.notebook.ts"),
  route("api/auth/register-options", "routes/api.auth.register-options.ts"),
  route("api/auth/register-verify", "routes/api.auth.register-verify.ts"),
  route("api/auth/login-options", "routes/api.auth.login-options.ts"),
  route("api/auth/login-verify", "routes/api.auth.login-verify.ts"),
  route("api/auth/magic-link", "routes/api.auth.magic-link.ts"),
  route("api/auth/magic-link/consume", "routes/api.auth.magic-link.consume.ts"),
  route("api/auth/logout", "routes/api.auth.logout.ts"),
  route("api/auth/session", "routes/api.auth.session.ts"),
  route("api/auth/passkeys", "routes/api.auth.passkeys.ts"),
  route("api/auth/passkeys/register-options", "routes/api.auth.passkeys.register-options.ts"),
  route("api/auth/passkeys/register-verify", "routes/api.auth.passkeys.register-verify.ts"),
  route("api/auth/passkeys/:id", "routes/api.auth.passkeys.$id.ts"),
  route("api/sync/push", "routes/api.sync.push.ts"),
  route("api/sync/pull", "routes/api.sync.pull.ts"),
  route("api/sync/files/upload", "routes/api.sync.files.upload.ts"),
  route("api/sync/files/download", "routes/api.sync.files.download.ts"),
] satisfies RouteConfig;
