-- Migration: Convert client-generated ID columns from uuid to text
-- These columns hold IDs generated by the client which may not be valid UUIDs
-- (e.g. "book-8b0331ab-...-35ff8042" from legacy data).
--
-- Server-generated IDs (user.id, session.id, challenge.id, user_id FKs) remain uuid.

BEGIN;

-- Drop foreign key constraints first (they reference the columns being altered)
ALTER TABLE readmax.reading_position DROP CONSTRAINT IF EXISTS reading_position_book_id_fkey;
ALTER TABLE readmax.highlight DROP CONSTRAINT IF EXISTS highlight_book_id_fkey;
ALTER TABLE readmax.notebook DROP CONSTRAINT IF EXISTS notebook_book_id_fkey;
ALTER TABLE readmax.chat_session DROP CONSTRAINT IF EXISTS chat_session_book_id_fkey;
ALTER TABLE readmax.chat_message DROP CONSTRAINT IF EXISTS chat_message_session_id_fkey;

-- Alter book.id from uuid to text
ALTER TABLE readmax.book
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id SET DATA TYPE TEXT USING id::text;

-- Alter reading_position.book_id
ALTER TABLE readmax.reading_position
    ALTER COLUMN book_id SET DATA TYPE TEXT USING book_id::text;

-- Alter highlight.id and highlight.book_id
ALTER TABLE readmax.highlight
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id SET DATA TYPE TEXT USING id::text,
    ALTER COLUMN book_id SET DATA TYPE TEXT USING book_id::text;

-- Alter notebook.book_id
ALTER TABLE readmax.notebook
    ALTER COLUMN book_id SET DATA TYPE TEXT USING book_id::text;

-- Alter chat_session.id and chat_session.book_id
ALTER TABLE readmax.chat_session
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id SET DATA TYPE TEXT USING id::text,
    ALTER COLUMN book_id SET DATA TYPE TEXT USING book_id::text;

-- Alter chat_message.session_id
ALTER TABLE readmax.chat_message
    ALTER COLUMN session_id SET DATA TYPE TEXT USING session_id::text;

-- Re-add foreign key constraints
ALTER TABLE readmax.reading_position
    ADD CONSTRAINT reading_position_book_id_fkey
    FOREIGN KEY (book_id) REFERENCES readmax.book(id);

ALTER TABLE readmax.highlight
    ADD CONSTRAINT highlight_book_id_fkey
    FOREIGN KEY (book_id) REFERENCES readmax.book(id);

ALTER TABLE readmax.notebook
    ADD CONSTRAINT notebook_book_id_fkey
    FOREIGN KEY (book_id) REFERENCES readmax.book(id);

ALTER TABLE readmax.chat_session
    ADD CONSTRAINT chat_session_book_id_fkey
    FOREIGN KEY (book_id) REFERENCES readmax.book(id);

ALTER TABLE readmax.chat_message
    ADD CONSTRAINT chat_message_session_id_fkey
    FOREIGN KEY (session_id) REFERENCES readmax.chat_session(id) ON DELETE CASCADE;

COMMIT;
